language: go

dist: trusty

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

addons:
  apt:
    packages:
    - php5-fpm
    - python3
    - python3.4-venv

env:
  global:
  - TEST_PHPFPM_PATH=/usr/sbin/php5-fpm

before_script:
  # for python3 tests
  - python3 -m venv myvenv
  - source myvenv/bin/activate
  - which python3 && python3 --version
  - which pip3 && pip3 --version
  - pip3 install -r example/python3/requirements.txt
  # for nodejs tests
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - nvm install 8 && npm install -g yarn
  - cd ./example/nodejs && yarn install && cd ../..

script:
  - go test -v -race ./...
